{
 "title": "Nextcloud",
 "description": "Dashboard showing metrics gathered by nextcloud-exporter from an Nextcloud instance.",
 "tags": [
  "prometheus",
  "nextcloud"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nextcloud_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Users and Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Daily Active Users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (nextcloud_active_users_daily_total{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (nextcloud_users_total{instance=\"$instance\"})",
     "legendFormat": "total ({{instance}})"
    },
    {
     "expr": "sum by(instance) (nextcloud_active_users_total{instance=\"$instance\"})",
     "legendFormat": "active ({{instance}})"
    }
   ]
  },
  {
   "title": "Files",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (nextcloud_files_total{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Shares", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Shares by Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(type) (nextcloud_shares_total{instance=\"$instance\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Federated Shares",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(direction) (nextcloud_shares_federated_total{instance=\"$instance\"})",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  { "title": "Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Installed Apps",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (nextcloud_apps_installed_total{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Updates",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (nextcloud_apps_updates_available_total{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Disk Space Left",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (nextcloud_free_space_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Nextcloud Versions (all instances)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(version) (nextcloud_system_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporter Versions (all instances)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(version) (nextcloud_exporter_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Environment Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "PHP Versions (all instances)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(version) (nextcloud_php_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Databases (all instances)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type, version) (nextcloud_database_info)",
     "legendFormat": "{{type}} {{version}}"
    }
   ]
  }
 ]
}